### ISSUE TITLE
Add valid language codes to README

### ISSUE THREAD

**Issue by biesbjerg** [enricodeleo/cordova-plugin-ios-localized-strings#1]
Hi! 

Just wanted to thank you for this plugin and suggest adding a list of valid language codes to the README.

### Available language codes
`no, en-US, en-CA, fi, ru, zh-Hans, nl-NL, zh-Hant, en-AU, id, de-DE, sv, ko, ms, pt-BR, el, es-ES, it, fr-CA, es-MX, pt-PT, vi, th, ja, fr-FR, da, tr, en-GB`

[Taken from Fastlane repo](https://github.com/fastlane/fastlane/blb/6da8810f3353bfb2f7095e7ecac8e0c544e4061d/deliver/README.md#available-language-codes)

**Comment by enricodeleo** [comment]
Thank you @biesbjerg please feel free to pull request any edit you might find helpful to others!
